/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,css}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "tertiary-fixed-dim": "#ffb690",
        "on-tertiary-container": "#ffcab0",
        "primary": "#0037b0",
        "on-error": "#ffffff",
        "surface-container-highest": "#dce2f7",
        "surface": "#f9f9ff",
        "on-surface-variant": "#434655",
        "on-primary-fixed-variant": "#0039b5",
        "inverse-surface": "#293040",
        "on-secondary": "#ffffff",
        "background": "#f9f9ff",
        "on-tertiary-fixed": "#341100",
        "surface-container": "#e9edff",
        "surface-dim": "#d3daef",
        "on-primary-container": "#cad3ff",
        "secondary-fixed": "#ffe083",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-container": "#1d4ed8",
        "inverse-primary": "#b7c4ff",
        "outline-variant": "#c4c5d7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container-high": "#e1e8fd",
        "surface-variant": "#dce2f7",
        "tertiary": "#753000",
        "secondary": "#735c00",
        "inverse-on-surface": "#edf0ff",
        "on-primary-fixed": "#001551",
        "on-surface": "#141b2b",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#231b00",
        "surface-tint": "#2151da",
        "on-secondary-container": "#6f5900",
        "primary-fixed-dim": "#b7c4ff",
        "outline": "#747686",
        "secondary-container": "#fed01b",
        "secondary-fixed-dim": "#eec200",
        "on-tertiary-fixed-variant": "#783200",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbca",
        "primary-fixed": "#dce1ff",
        "on-background": "#141b2b",
        "tertiary-container": "#9a4200",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "3rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-code": ["JetBrains Mono"],
        "body-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-badge": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "label-code": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-badge": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
